# Generated by Django 5.1.7 on 2025-03-15 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "code",
                    models.CharField(
                        blank=True,
                        default="AAA",
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=20)),
            ],
            options={"ordering": ["code"],},
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "code",
                    models.CharField(
                        blank=True,
                        default="AAA",
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=20)),
                (
                    "avgRating",
                    models.IntegerField(
                        choices=[(-1, -1), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        default=-1,
                    ),
                ),
            ],
            options={"ordering": ["code"],},
        ),
        migrations.CreateModel(
            name="ModuleInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(default="2024")),
                ("semester", models.IntegerField(choices=[(1, 1), (2, 2)])),
                (
                    "code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cw1app.module"
                    ),
                ),
                ("leaders", models.ManyToManyField(to="cw1app.professor")),
            ],
            options={"ordering": ["code"],},
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(default="2024")),
                ("semester", models.IntegerField(choices=[(1, 1), (2, 2)])),
                (
                    "score",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cw1app.module"
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cw1app.professor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("user", "professor", "module", "year", "semester", "score")
                },
            },
        ),
    ]
